package LectureNotes;

public class A03_MavenIntroduction {
    /*
    https://github.com/SeleniumHQ/selenium/wiki

https://seleniumhq.github.io/docs/index.html

https://www.seleniumhq.org/docs/


_________




HOW APPLICATIONS ARE WRITTEN AND DEPLOYED?


we have requirements

choose tools

develop the code

create project
create some package

write some code
write unit test for code
compile
run unit tests
push your code / deploy -->


BUIlD PROCESS


testing

production
____


Tools used for automating the build proccesses: Maven, Gradle, Ant.


Maven is a build autamtion tools specific to Java environment

______

root folder: highest level folder in your computer, oni windows it the the C: drive,
in mac it is the root folder

home folder == home directory
user folder == user directory

user folder --> special directory created for the account you loggin as

for my Mac : /Users/cybertekschool

for windows: C:\Users\cybertekschool

tools like maven are installed in some directory, but they will use the user directory for saving their things

____


mvn archetype:generate --> maven, can you please create a new project from the samples you have.

Next do not enter any number, just hit enter, it means use the default one.


for package enter com.cybertek
for artifact-id, enter first-maven-app

keep hitting enter until you see BUILD SUCCESS

all maven commands start with mvn.
groupId --> name of the package
artifactId --> name of the project




BUILD SUCCESS
BUILD FAILIURE --> all maven commands will end with either of this outcome

maven lifecycle = maven goal --> maven operations for compiling, building, testing, deploying the project

mvn compile: it will compile to project
mvn test: runs the units of the project


in order run any maven lifecycle, we have to be in the project folder. project is highest level folder. is is a package with the project name.

in order run any maven lifecycle, we have to be able to see pom.xml when we do ls / dir
we need to change directory using : cd first-maven-app


target: all the compiled code and reports generated by maven will be stored here

mvn clean: used to delete the target folder and all generated sources, reports


Why do we need maven:
we will run tests and get reports using maven in the future by using the mvn test command

_____


Create maven project using intellij
1. open intellij
2. File --> New --> Project
3. Select maven
4. Cclick Next
5. ENter group id- com.cybertel
6. enter artifact-id: maven-project-z
7. hit next
8. Hit Finish


CLick Enable auto import


___

pom.xml --> is created when we create any maven project, it is always on the top level project
pom file is the most important file in any maven project, is ithe command center of the project,
in any maven project, inside src, we ahve main and test folders.
all the application code is written in the main folder
all the tests (unit tests, functrional selenium) are written in the test folder
In pom file we manage dependencies for the project, we can external libraries to our project using the pom file.


Create a package inside the test/java: com.cybertek.
     */
}
