package LectureNotes;

public class A08_Iframe_Tabs {
    /*
     IFRAMES
    1. create a new class IframeDemo
    2. go to url https://the-internet.herokuapp.com/tinymce
    3. enter text in the text editor
    what to if I get no such element exception:
    1. check your locator
    2. check your wait
    3. check there is an iframe
    iframe/frame: they are used to put one html document inside another html document.
    html
    title
    text
    link
    iframe
    html
    link
    selenium can deal with only one html document at a time.
    selenium can see only one html document at a time.
    selenium can see the iframe element, but cannot see whats inside it.
    in order to deal with iframe, we need to change the focus of selenium into the iframe. we need to swtich to iframe
    we can switch to iframe using : driver.switchTo().frame()
    when we swtich into any iframe, selenium cannot see the contents of the previous html. we need to swtich back to we came from
    we can switch back to previous frame using :
    NESTED IFRAMES
    Some pages they have multiple iframes:
    html : default content
    iframe 1frame 1
    html 1
    iframe 2frame 2
    html 2
    frame 2 is inside frame 1.
    how to get the frame 2:
    1. switch to iframe 1
    2. switch to iframe 2
    how do I go back from frame 2 to the default frame:
    2 options.
    1. driver.switchTo().defaultContent() : takes us back to the top level, to the default content.
    if there are multiple iframe, it it dfoes not matter, will go to the top level
    2. driver.switchTo().parentFrame();  --> it takes you to the parent of the current frame.
    driver.switchTo().parentFrame();  it takes me from iframe 2 to iframe 1
    driver.switchTo().parentFrame();  it takes me from iframe 1 to default content
    MULTIPLE IFRAMES
    html default content
    frame 1
    frame 2
    frame 3
    frame 4
    frame 5
    ___
    how to jump from frame 2 to iframe 4?
    frame 2 --> default --> frame 3 ---> frame 4
    __
    when going back we can use default contect to jump multiple levels.
    when go inside  nested frame, we have to swtich one by one
    What are the different ways of switching to frames?
    1. locate the frame element and switch to the element, we pass the webelement as a parameter
            WebElement iframe = driver.findElement(By.id("mce_0_ifr"));
    driver.switchTo().frame(iframe);
    2. usnig the name or id of the iframe element
    driver.switchTo().frame("mce_0_ifr");
    3. using index
    driver.switchTo().frame(1);
    TABS/WINDOWS
    Test case:
    go to http://the-internet.herokuapp.com/windows
    click on click "Click here"
    verify that new title is "New Window"
    verify that new title is not "The Internet"
    By default, selenium can only handle/see one tab at a time. if we wont to do anything in the new, we have to switch to it first
    driver.getWindowHandles().  --> give the IDs of all currently open tabs
    ___
    Set is juuuuust like ArrayList without duplicates values, also it does get method
    When we want to change tabs, we use the windowshadles to ochage. we get the windowshadles from the getWindowHandles.
    getWindowHandles returns a set, they guy who wrote selenium did it like this. thats i am using it like this
    For selenium, there is not difference between tab and windwow
    driver.close() --> closes the current tab controlled by webdirver.
    driver.quit(). --> closes all the open tabs, we cannot use the webdriver object again, we have to initilize it one more time to use it
    POP UPS
    1. HTML POP UPS
    some pop up have html, meaning we can right click and inspect. if we can right click and inspect, it emans it is generated by HTML. they are html pop up
    how to handle:
    2 JAVASCRIPTS ALERTS/POP UP
    when we have JS alerts, we need to create an alert obejct to handle it:
    Alert alert = driver.switchTo().alert();
    We have to have an actual alert on the page to use this link, if there is not JS alert we get NoAlertPresentException
     */
}
